version: '3.8'

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
      args:
        - MYSQL_DATABASE=networkapp
        - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile-app
#    ports:
#      - '8080:8080'
#    depends_on:
#      - db

